
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { AddInvestmentSchema, type AddInvestmentFormValues, investmentTypes } from "@/lib/schemas";
import { useInvestments } from "@/hooks/use-investments";
import { useToast } from "@/hooks/use-toast";
import { v4 as uuidv4 } from "uuid";
import { currencyFluctuationAnalysis } from "@/ai/flows/currency-fluctuation-analysis";
import type { CurrencyFluctuationAnalysisInput, CurrencyFluctuationAnalysisOutput } from "@/ai/flows/currency-fluctuation-analysis";
import React, { useState, useEffect } from "react";
import { CurrencyAnalysisDisplay } from "./currency-analysis-display";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2 } from "lucide-react";
import { useListedStocks } from "@/hooks/use-listed-stocks";
import type { ListedStock, StockInvestment } from "@/lib/types";
import { useSearchParams, useRouter } from "next/navigation";

// Helper function to get current date in YYYY-MM-DD format
const getCurrentDate = () => {
  const date = new Date();
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const initialFormValues: AddInvestmentFormValues = {
  // name: "", // Will be auto-generated by form submission logic
  amountInvested: 0, // For non-stock types, calculated for stocks
  purchaseDate: getCurrentDate(),
  type: undefined,
  selectedStockId: undefined,
  numberOfShares: '', // Handled as string for input, coerced by Zod
  purchasePricePerShare: '', // Handled as string for input, coerced by Zod
  purchaseFees: 0, // Default to 0, can be changed
  quantityInGrams: '', // Handled as string for input, coerced by Zod
  isPhysicalGold: true,
  currencyCode: "",
  baseCurrency: "",
  currentExchangeRate: '', // Handled as string for input, coerced by Zod
  propertyAddress: "",
  propertyType: undefined,
  issuer: "",
  interestRate: '', // Handled as string for input, coerced by Zod
  maturityDate: '',
};


export function AddInvestmentForm() {
  const { addInvestment } = useInvestments();
  const { toast } = useToast();
  const router = useRouter();
  const searchParams = useSearchParams();
  const preSelectedStockId = searchParams.get('stockId');

  const [isLoadingAi, setIsLoadingAi] = useState(false);
  const [aiAnalysisResult, setAiAnalysisResult] = useState<CurrencyFluctuationAnalysisOutput | null>(null);
  const { listedStocks, isLoading: isLoadingListedStocks, error: listedStocksError, getListedStockById } = useListedStocks();
  const [preSelectedStockDetails, setPreSelectedStockDetails] = useState<ListedStock | null>(null);


  const form = useForm<AddInvestmentFormValues>({
    resolver: zodResolver(AddInvestmentSchema),
    defaultValues: {
      ...initialFormValues,
      // Type and selectedStockId will be set in useEffect if preSelectedStockId exists
    },
  });

  const selectedType = form.watch("type");

  useEffect(() => {
    if (preSelectedStockId) {
      getListedStockById(preSelectedStockId).then(stock => {
        if (stock) {
          setPreSelectedStockDetails(stock);
          form.setValue("type", "Stocks");
          form.setValue("selectedStockId", preSelectedStockId);
          // Name is auto-generated in onSubmit
        } else {
          // Handle case where preSelectedStockId is invalid
          toast({
            title: "Error",
            description: "Pre-selected stock not found. Please select a stock manually or go back.",
            variant: "destructive",
          });
          router.replace('/investments/add'); // Or redirect to a more appropriate page
        }
      });
    } else {
      // Reset preSelectedStockDetails if no stockId is in URL (e.g., user navigates away and back)
      setPreSelectedStockDetails(null);
      // Clear related stock fields if type is changed away from stocks or stock is deselected manually
      if (form.getValues("type") !== "Stocks") {
        form.setValue("selectedStockId", undefined);
      }
    }
  }, [preSelectedStockId, getListedStockById, form, toast, router]);


  async function onSubmit(values: AddInvestmentFormValues) {
    setIsLoadingAi(false);
    setAiAnalysisResult(null);

    const investmentId = uuidv4();
    let investmentName = ""; 

    let newInvestment: any = { // Base structure, will be typed more specifically
      id: investmentId,
      type: values.type,
      // purchaseDate will be added specifically for stocks or general below
    };

    let analysisResult: CurrencyFluctuationAnalysisOutput | undefined = undefined;

    if (values.type === "Stocks") {
      const stockToProcessId = values.selectedStockId || preSelectedStockId; // Ensure we use the ID correctly
      const selectedStock = listedStocks.find(stock => stock.id === stockToProcessId);

      if (!selectedStock) {
        toast({
          title: "Error",
          description: "Selected stock not found. Please try again.",
          variant: "destructive",
        });
        return;
      }
      const numShares = typeof values.numberOfShares === 'number' ? values.numberOfShares : parseFloat(values.numberOfShares || '0');
      const pricePerShare = typeof values.purchasePricePerShare === 'number' ? values.purchasePricePerShare : parseFloat(values.purchasePricePerShare || '0');
      // Ensure fees is a number, defaulting to 0 if undefined or NaN from coercion
      const fees = typeof values.purchaseFees === 'number' ? values.purchaseFees : (parseFloat(String(values.purchaseFees)) || 0);


      const calculatedAmountInvested = (numShares * pricePerShare) + fees;
      
      investmentName = `${selectedStock.name} Purchase`; // Programmatic name

      newInvestment = {
        ...newInvestment,
        name: investmentName,
        amountInvested: calculatedAmountInvested,
        purchaseDate: values.purchaseDate, // Specific for stocks, taken from its section
        actualStockName: selectedStock.name,
        tickerSymbol: selectedStock.symbol,
        stockLogoUrl: selectedStock.logoUrl,
        numberOfShares: numShares,
        purchasePricePerShare: pricePerShare,
        purchaseFees: fees,
      } as StockInvestment; // Cast to specific type
    } else {
      // For non-stock types
      newInvestment.amountInvested = typeof values.amountInvested === 'number' ? values.amountInvested : parseFloat(String(values.amountInvested || '0'));
      investmentName = `${values.type} Investment on ${values.purchaseDate}`;
      newInvestment.name = investmentName;
      newInvestment.purchaseDate = values.purchaseDate; // General purchase date

      if (values.type === "Gold") {
        newInvestment = {
          ...newInvestment,
          quantityInGrams: typeof values.quantityInGrams === 'number' ? values.quantityInGrams : parseFloat(values.quantityInGrams || '0'),
          isPhysical: values.isPhysicalGold,
        };
      } else if (values.type === "Currencies") {
        newInvestment = {
          ...newInvestment,
          currencyCode: values.currencyCode,
          baseCurrency: values.baseCurrency,
          currentExchangeRate: typeof values.currentExchangeRate === 'number' ? values.currentExchangeRate : parseFloat(values.currentExchangeRate || '0'),
        };

        if (values.currencyCode && values.baseCurrency && values.currentExchangeRate && newInvestment.amountInvested) {
          setIsLoadingAi(true);
          try {
            const aiInput: CurrencyFluctuationAnalysisInput = {
              transactionCurrency: values.currencyCode,
              transactionAmount: newInvestment.amountInvested,
              transactionDate: values.purchaseDate,
              baseCurrency: values.baseCurrency,
              currentExchangeRate: newInvestment.currentExchangeRate,
            };
            analysisResult = await currencyFluctuationAnalysis(aiInput);
            setAiAnalysisResult(analysisResult);
          } catch (error) {
            console.error("Currency analysis AI error:", error);
            toast({
              title: "AI Analysis Failed",
              description: "Could not perform currency fluctuation analysis.",
              variant: "destructive",
            });
          } finally {
            setIsLoadingAi(false);
          }
        }
      } else if (values.type === "Real Estate") {
        newInvestment = {
          ...newInvestment,
          propertyAddress: values.propertyAddress,
          propertyType: values.propertyType,
        }
      } else if (values.type === "Debt Instruments") {
        newInvestment = {
          ...newInvestment,
          issuer: values.issuer,
          interestRate: typeof values.interestRate === 'number' ? values.interestRate : parseFloat(values.interestRate || '0'),
          maturityDate: values.maturityDate,
        }
      }
    }
    
    addInvestment(newInvestment, analysisResult); // Pass the fully constructed object
    toast({
      title: "Investment Added",
      description: `${newInvestment.name} (${values.type}) has been successfully added.`,
    });

    const resetType = preSelectedStockId ? "Stocks" : undefined;
    const resetStockId = preSelectedStockId ? preSelectedStockId : undefined;
    
    form.reset({
      ...initialFormValues,
      type: resetType, // Keep type if it was pre-selected for stocks
      selectedStockId: resetStockId, // Keep stockId if it was pre-selected
      // name: "", // Name is auto-generated, so no need to reset it in form values
    });
    // If not pre-selected stock, or if we want to clear the form completely after ANY add:
    if (!preSelectedStockId) {
        setPreSelectedStockDetails(null); 
        router.replace('/investments/add'); 
    }
    // For pre-selected stock, we might want to keep the context (form pre-filled for another buy of same stock)
    // or clear it. Current reset logic will keep it pre-filled.

    if (!analysisResult) { // Ensure AI analysis display is cleared if no new analysis was run
       setAiAnalysisResult(null);
    }
  }

  const handleNumericInputChange = (field: any, value: string) => {
    if (value === '') {
      field.onChange(undefined); // Use undefined for empty for better Zod optional handling
    } else {
      const parsedValue = parseFloat(value);
      // For react-hook-form, it's often better to store undefined if parse fails,
      // Zod can then handle the coercion or error.
      field.onChange(isNaN(parsedValue) ? undefined : parsedValue);
    }
  };
  

  const pageTitle = preSelectedStockId && preSelectedStockDetails 
    ? `Buy: ${preSelectedStockDetails.name}` 
    : "Add New Investment";

  const showGeneralPurchaseDate = selectedType !== "Stocks" && !preSelectedStockId;
  const showInvestmentTypeSelector = !preSelectedStockId;


  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center">
            {preSelectedStockId && isLoadingListedStocks && !preSelectedStockDetails ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : null}
            {pageTitle}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

              {showInvestmentTypeSelector && (
                <FormField
                  control={form.control}
                  name="type"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Investment Type</FormLabel>
                      <Select
                        onValueChange={(value) => {
                          field.onChange(value);
                          if (value !== "Stocks") {
                              form.setValue("selectedStockId", undefined);
                              setPreSelectedStockDetails(null); // Clear stock details if type changes from stocks
                          }
                          // Name is auto-generated
                        }}
                        value={field.value || ""}
                      >
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select an investment type" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {investmentTypes.map((type) => (
                            <SelectItem key={type} value={type}>
                              {type}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {selectedType !== "Stocks" && ( 
                 <FormField
                    control={form.control}
                    name="amountInvested"
                    render={({ field }) => (
                    <FormItem>
                        <FormLabel>Total Amount Invested</FormLabel>
                        <FormControl>
                        <Input type="number" step="any" placeholder="e.g., 10000" {...field}
                            value={field.value ?? ''} 
                            onChange={e => handleNumericInputChange(field, e.target.value)} />
                        </FormControl>
                        <FormDescription>Total cost including any fees.</FormDescription>
                        <FormMessage />
                    </FormItem>
                    )}
                />
              )}

              {showGeneralPurchaseDate && (
                <FormField
                  control={form.control}
                  name="purchaseDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Purchase Date</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} value={field.value || getCurrentDate()} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}
            </div>

            {selectedType === "Stocks" && (
              <div className="space-y-6 mt-6 p-6 border rounded-md">
                <h3 className="text-lg font-medium text-primary">Stock Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {!preSelectedStockId && ( // Only show selector if not pre-selected
                    <FormField
                      control={form.control}
                      name="selectedStockId"
                      render={({ field }) => (
                        <FormItem className="md:col-span-2">
                          <FormLabel>Select Stock</FormLabel>
                          <Select
                            onValueChange={(value) => {
                                field.onChange(value);
                                const stock = listedStocks.find(s => s.id === value);
                                setPreSelectedStockDetails(stock || null);
                                // Name is auto-generated
                            }}
                            value={field.value || ""}
                            disabled={isLoadingListedStocks || !!listedStocksError || listedStocks.length === 0}
                          >
                            <FormControl>
                              <SelectTrigger>
                                <SelectValue placeholder={
                                  isLoadingListedStocks ? "Loading stocks..." :
                                  listedStocksError ? "Error loading stocks" :
                                  listedStocks.length === 0 ? "No stocks available" :
                                  "Select a stock from the list"
                                } />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              {isLoadingListedStocks && <SelectItem value="loading" disabled>Loading...</SelectItem>}
                              {listedStocksError && <SelectItem value="error" disabled>Could not load stocks.</SelectItem>}
                              {!isLoadingListedStocks && !listedStocksError && listedStocks.length === 0 && <SelectItem value="no-stocks" disabled>No stocks found. Add them via admin.</SelectItem>}
                              {listedStocks.map((stock) => (
                                <SelectItem key={stock.id} value={stock.id}>
                                  {stock.name} ({stock.symbol}) - {stock.market}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  )}
                   {preSelectedStockDetails && ( // Display details if a stock is selected/pre-selected
                     <div className="md:col-span-2 p-3 bg-muted/50 rounded-md">
                        <p className="text-sm font-medium">Selected Stock: {preSelectedStockDetails.name} ({preSelectedStockDetails.symbol})</p>
                        <p className="text-xs text-muted-foreground">Current Market Price: {preSelectedStockDetails.price.toLocaleString(undefined, {style: 'currency', currency: preSelectedStockDetails.currency})}</p>
                     </div>
                   )}
                  <FormField control={form.control} name="numberOfShares" render={({ field }) => (
                      <FormItem><FormLabel>Number of Securities</FormLabel><FormControl><Input type="number" step="any" placeholder="e.g., 100" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} /></FormControl><FormMessage /></FormItem>
                    )} />
                  <FormField control={form.control} name="purchasePricePerShare" render={({ field }) => (
                      <FormItem><FormLabel>Purchase Price (per security)</FormLabel><FormControl><Input type="number" step="any" placeholder="e.g., 150.50" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} /></FormControl><FormMessage /></FormItem>
                    )} />
                  <FormField
                    control={form.control}
                    name="purchaseFees"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Purchase Fees (optional)</FormLabel>
                        <FormControl>
                          <Input type="number" step="any" placeholder="e.g., 5.00" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} />
                        </FormControl>
                        <FormDescription>Brokerage or transaction fees for this purchase.</FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="purchaseDate" // Moved here for stocks
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Purchase Date</FormLabel>
                        <FormControl>
                          <Input type="date" {...field} value={field.value || getCurrentDate()}/>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>
            )}

            {selectedType === "Gold" && !preSelectedStockId && (
               <div className="space-y-6 mt-6 p-6 border rounded-md">
                <h3 className="text-lg font-medium text-primary">Gold Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <FormField control={form.control} name="quantityInGrams" render={({ field }) => (
                      <FormItem><FormLabel>Quantity (grams)</FormLabel><FormControl><Input type="number" step="any" placeholder="e.g., 50" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} /></FormControl><FormMessage /></FormItem>
                    )} />
                  <FormField control={form.control} name="isPhysicalGold" render={({ field }) => (
                      <FormItem className="flex flex-row items-start space-x-3 space-y-0 rounded-md border p-4"><FormControl><Input type="checkbox" checked={!!field.value} onChange={e => field.onChange(e.target.checked)} className="h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground" /></FormControl><div className="space-y-1 leading-none"><FormLabel>Is this physical gold?</FormLabel><FormDescription>Uncheck for Gold ETFs, Digital Gold etc.</FormDescription></div></FormItem>
                    )} />
                </div>
              </div>
            )}

            {selectedType === "Currencies" && !preSelectedStockId && (
              <div className="space-y-6 mt-6 p-6 border rounded-md">
                <h3 className="text-lg font-medium text-primary">Currency Details</h3>
                 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  <FormField control={form.control} name="currencyCode" render={({ field }) => (
                      <FormItem><FormLabel>Transaction Currency Code</FormLabel><FormControl><Input placeholder="e.g., USD" {...field} value={field.value || ''} /></FormControl><FormMessage /></FormItem>
                    )} />
                  <FormField control={form.control} name="baseCurrency" render={({ field }) => (
                      <FormItem><FormLabel>Base Currency Code (for comparison)</FormLabel><FormControl><Input placeholder="e.g., EUR" {...field} value={field.value || ''} /></FormControl><FormMessage /></FormItem>
                    )} />
                   <FormField control={form.control} name="currentExchangeRate" render={({ field }) => (
                      <FormItem><FormLabel>Current Exchange Rate (to Base)</FormLabel><FormControl><Input type="number" step="any" placeholder="e.g., 0.92" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} /></FormControl><FormDescription>Needed for AI fluctuation analysis.</FormDescription><FormMessage /></FormItem>
                    )} />
                </div>
              </div>
            )}

            {selectedType === "Real Estate" && !preSelectedStockId && (
              <div className="space-y-6 mt-6 p-6 border rounded-md">
                <h3 className="text-lg font-medium text-primary">Real Estate Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <FormField control={form.control} name="propertyAddress" render={({ field }) => (
                    <FormItem><FormLabel>Property Address</FormLabel><FormControl><Input placeholder="e.g., 123 Main St, Anytown" {...field} value={field.value || ''}/></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="propertyType" render={({ field }) => (
                    <FormItem><FormLabel>Property Type</FormLabel><Select onValueChange={field.onChange} value={field.value || ""}><FormControl><SelectTrigger><SelectValue placeholder="Select property type" /></SelectTrigger></FormControl><SelectContent><SelectItem value="Residential">Residential</SelectItem><SelectItem value="Commercial">Commercial</SelectItem><SelectItem value="Land">Land</SelectItem></SelectContent></Select><FormMessage /></FormItem>
                  )} />
                </div>
              </div>
            )}

            {selectedType === "Debt Instruments" && !preSelectedStockId && (
              <div className="space-y-6 mt-6 p-6 border rounded-md">
                <h3 className="text-lg font-medium text-primary">Debt Instrument Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  <FormField control={form.control} name="issuer" render={({ field }) => (
                    <FormItem><FormLabel>Issuer</FormLabel><FormControl><Input placeholder="e.g., Government Bonds" {...field} value={field.value || ''} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="interestRate" render={({ field }) => (
                    <FormItem><FormLabel>Interest Rate (%)</FormLabel><FormControl><Input type="number" step="any" placeholder="e.g., 5.5" {...field} value={field.value ?? ''} onChange={e => handleNumericInputChange(field, e.target.value)} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="maturityDate" render={({ field }) => (
                    <FormItem><FormLabel>Maturity Date</FormLabel><FormControl><Input type="date" {...field} value={field.value || ''} /></FormControl><FormMessage /></FormItem>
                  )} />
                </div>
              </div>
            )}

            {isLoadingAi && (
              <div className="flex items-center justify-center p-4_my-4 text-muted-foreground">
                <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                Performing currency analysis...
              </div>
            )}

            {aiAnalysisResult && selectedType === "Currencies" && (
              <CurrencyAnalysisDisplay result={aiAnalysisResult} />
            )}

            <Button type="submit" className="w-full md:w-auto" disabled={form.formState.isSubmitting || isLoadingAi || (selectedType === "Stocks" && (isLoadingListedStocks || !!listedStocksError))}>
              {form.formState.isSubmitting || isLoadingAi ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              {preSelectedStockId ? "Buy Stock" : "Add Investment"}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}

